export const SEARCH_REPOSITORIES = 'SEARCH_REPOSITORIES';
export const GET_REPOS_DETAIL = 'GET_REPOS_DETAIL';
export const CLEAR_REPOSITORIES = 'CLEAR_REPOSITORIES';
export const SET_LOADING = 'SET_LOADING';